const actionTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SET_BUCKET: "SET_BUCKET",
    SET_CURRENT_BUCKET: "SET_CURRENT_BUCKET",
    SET_TODO: "SET_TODO",
    SET_CURRENT_TODO: "SET_CURRENT_TODO",
    LOGOUT: "LOGOUT"
};

export default actionTypes;